<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudiator" nsURI="http://www.example.org/cloudiator" nsPrefix="cloudiator">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CloudiatorModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clouds" upperBound="-1"
        eType="#//Cloud" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" eType="#//Cloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//Image"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" eType="#//Hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"
        volatile="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="hardware.prices->select(p | p.image = self.image and p.location = self.location)->first().price"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operatingSystem" eType="#//OperatingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" lowerBound="1" eType="#//Cloud"
        changeable="false" eOpposite="#//Cloud/images"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ram" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//FloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prices" lowerBound="1"
        upperBound="-1" eType="#//Price" eOpposite="#//Price/hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" lowerBound="1" eType="#//Cloud"
        changeable="false" eOpposite="#//Cloud/hardwareList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" lowerBound="1" eType="#//Cloud"
        changeable="false" eOpposite="#//Cloud/locations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CloudType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true" eOpposite="#//Location/cloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareList" upperBound="-1"
        eType="#//Hardware" containment="true" eOpposite="#//Hardware/cloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="images" upperBound="-1"
        eType="#//Image" containment="true" eOpposite="#//Image/cloud"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" eType="#//OSFamily"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="architecture" eType="#//OSArchitecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CloudType">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PRIVATE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSArchitecture">
    <eLiterals name="AMD64"/>
    <eLiterals name="I368" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSFamily">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="AIX" value="1"/>
    <eLiterals name="ARCH" value="2"/>
    <eLiterals name="CENTOS" value="3"/>
    <eLiterals name="DARWIN" value="4"/>
    <eLiterals name="DEBIAN" value="5"/>
    <eLiterals name="ESX" value="6"/>
    <eLiterals name="FEDORA" value="7"/>
    <eLiterals name="FREEBSD" value="8"/>
    <eLiterals name="GENTOO" value="9"/>
    <eLiterals name="HPUX" value="10"/>
    <eLiterals name="COREOS" value="11"/>
    <eLiterals name="AMZN_LINUX" value="12"/>
    <eLiterals name="MANDRIVA" value="13"/>
    <eLiterals name="NETBSD" value="14"/>
    <eLiterals name="OEL" value="15"/>
    <eLiterals name="OPENBSD" value="16"/>
    <eLiterals name="RHEL" value="17"/>
    <eLiterals name="SCIENTIFIC" value="18"/>
    <eLiterals name="CEL" value="19"/>
    <eLiterals name="SLACKWARE" value="20"/>
    <eLiterals name="SOLARIS" value="21"/>
    <eLiterals name="SUSE" value="22"/>
    <eLiterals name="TURBOLINUX" value="23"/>
    <eLiterals name="CLOUD_LINUX" value="24"/>
    <eLiterals name="UBUNTU" value="25"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Price">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" lowerBound="1"
        eType="#//Hardware" eOpposite="#//Hardware/prices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Image"/>
  </eClassifiers>
</ecore:EPackage>
