<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudiator" nsURI="http://www.example.org/cloudiator" nsPrefix="cloudiator">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CloudiatorModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="images" upperBound="-1"
        eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareList" upperBound="-1"
        eType="#//Hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clouds" upperBound="-1"
        eType="#//Cloud" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" eType="#//Cloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//Image"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" eType="#//Hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ram" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CloudType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="images" upperBound="-1"
        eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareList" upperBound="-1"
        eType="#//Hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CloudType">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PRIVATE" value="1"/>
  </eClassifiers>
</ecore:EPackage>
